# Generated by Django 6.0.1 on 2026-01-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
